GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "test",
    "number": "1234567890"
}
###
PUT http://localhost:3001/api/persons/64d74e1e6063b880e1727465 HTTP/1.1
content-type: application/json

{
    "name": "what",
    "number": "to tez"
}
###
DELETE http://localhost:3001/api/persons/64d1525816e574b22db46c92 HTTP/1.1